CREATE TABLE PRODUCT_OUTER(
    PRODUCT VARCHAR(50),
    RATIO NUMBER
    );

SELECT *
FROM PRODUCT_OUTER

INSERT INTO PRODUCT_OUTER
VALUES ('A',4.5)

INSERT INTO PRODUCT_OUTER
VALUES ('D',3)

CREATE TABLE PRODUCT_INNER(
    PRODUCT VARCHAR(50),
    RATIO NUMBER
    );
    
SELECT *
FROM PRODUCT_INNER

INSERT INTO PRODUCT_INNER
VALUES ('E',5)

SELECT A.PRODUCT, A.RATIO
FROM PRODUCT_OUTER A
INNER JOIN PRODUCT_INNER B 
ON A.PRODUCT = B.PRODUCT;

CREATE TABLE REGION_ORG(
    REGION VARCHAR(50),
    RATIO NUMBER
    );

SELECT *
FROM REGION_ORG

INSERT INTO REGION_ORG
VALUES ('TEXAS',50)

INSERT ALL 
    INTO KOPO_REGION_MASTER_ORG
    VALUES(REGIONID, DETAILS, UPDTTIME)
    INTO KOPO_REGION_MASTER_ORG2
    VALUES(REGIONID, DETAILS, UPDTTIME)
    

CREATE TABLE REGION_UPDATE(
    REGION VARCHAR(50),
    RATIO NUMBER
    );
    
SELECT *
FROM REGION_UPDATE

INSERT INTO REGION_UPDATE
VALUES ('NEW', 20)

MERGE INTO REGION_ORG A
    USING REGION_UPDATE B
    ON(A.REGION = B.REGION)
WHEN MATCHED THEN
UPDATE SET A.RATIO = B.RATIO
WHEN NOT MATCHED THEN 
INSERT(A.REGION, A.RATIO) VALUES(B. REGION, B.RATIO)

SELECT *
FROM REGION_ORG

CREATE TABLE KOPO_HAITEAM(
    COL1 VARCHAR2(100),
    COL2 CLOB,
    COL3 NUMBER
    );
    
SELECT *
FROM KOPO_HAITEAM
    
SELECT *
FROM KOPO_HAITEAM

-- 데이터를 전체 행 넣을경우
INSERT INTO {테이블명} VALUES { 테이블 내 컬럼값}

INSERT INTO KOPO_HAITEAM VALUES('HAITEAM','CONTENTS',15)

-- 특정컬럼에만 넣을경우
INSERT INTO {테이블명} {컬럼명} VALUES { 넣을값}

INSERT INTO KOPO_HAITEAM (COL2, COL3)
VALUES('CONTENTS', 15)

INSERT INTO KOPO_HAITEAM (COL2, COL3)
VALUES('CONTENTS', NULL)

INSERT INTO KOPO_HAITEAM (COL2, COL3)
VALUES('CONTENTS', 'NULL')

SELECT *
FROM KOPO_HAITEAM

CREATE TABLE KOPO_REGION_MASTER(
    REGIONID VARCHAR2(100),
    DETAILS CLOB,
    UPDTTIME NUMBER
    );

INSERT INTO KOPO_REGION_MASTER VALUES('A01','미국',20230828)

INSERT INTO KOPO_REGION_MASTER VALUES('A01','미국',20230832)

SELECT 'A02' AS REGIONID,
       '프랑스' AS DETAILS,
       UPDTTIME
FROM KOPO_REGION_MASTER

SELECT *
FROM KOPO_REGION_MASTER

--UPDATE 명령 사용하기

SELECT *
FROM KOPO_REGIONID_MASTER

UPDATE KOPO_REGION_MASTER
SET DETAILS 'AMERICA'

WHERE 1=1
AND REGIONID = 'A01'

SELECT *
FROM KOPO_REGIONID_MASTER
 