SELECT *
FROM KOPO_PRODUCT_VOLUME

SELECT REGIONID,PRODUCTGROUP
FROM KOPO_PRODUCT_VOLUME

CREATE TABLE KOPO_DOHMISOL
(
 REGIONID VARCHAR(200),
 PRODUCTGROUP VARCHAR(200),
 YEARWEEK VARCHAR(200),
 VOLUME NUMBER
)

CREATE TABLE KOPO_MS
(
 REGIONID VARCHAR(200),
 PRODUCTGROUP VARCHAR(200),
 YEARWEEK VARCHAR(200),
 VOLUME NUMBER
 )
 
 SELECT *
 FROM KOPO_MS
 
CREATE TABLE KOPO_MS1
(
 지역번호 VARCHAR(200),
 상품번호 VARCHAR(200),
 주차   NUMBER,
 물량    NUMBER,
 행사번호 VARCHAR(200)
 )
 
 SELECT *
 FROM KOPO_MS1
 
 CREATE TABLE KOPO_MS2
(
 지역번호 VARCHAR(200),
 상품번호 VARCHAR(200),
 주차   NUMBER,
 물량    NUMBER,
 행사번호 VARCHAR(200)
 constraint pk_kopo_ms2 primary key(지역번호,상품번호)
 );

 CREATE TABLE KOPO_MS6 (
    지역번호 VARCHAR(200),
    상품번호 VARCHAR(200),
    주차 NUMBER,
    물량 NUMBER,
    행사번호 VARCHAR(200),
    CONSTRAINT pk_kopo_ms2 PRIMARY KEY (지역번호, 상품번호)
);

SELECT *
FROM KOPO_MS6

CREATE TABLE KOPO_MS10 (
    지역번호 VARCHAR(200),
    상품번호 VARCHAR(200),
    주차 NUMBER,
    물량 NUMBER,
    행사번호 VARCHAR(200),
    CONSTRAINT pk_kopo_ms10 PRIMARY KEY (지역번호, 상품번호)
);

SELECT *
FROM KOPO_MS10

CREATE TABLE KOPO_MS11(
    지역번호 VARCHAR(200),
    상품번호 VARCHAR(200),
    주차 NUMBER,
    물량 NUMBER,
    행사번호 VARCHAR(200),
    CONSTRAINT pk_kopo_ms11 PRIMARY KEY (지역번호, 상품번호)
);

SELECT *
FROM KOPO_PRODUCT_VOLUME

CREATE TABLE KOPO_PRODUCT_VOLUME45(
    REGIONID VARCHAR(200),
    PRODUCTGROUP VARCHAR(200),
    YEARWEEK VARCHAR(200),
    VOLUME NUMBER NOT NULL,
CONSTRAINT pk_kopo_product_volume45 primary key(regionid, yearweek)
)

SELECT *
FROM KOPO_PRODUCT_VOLUME45

insert into KOPO_PRODUCT_VOLUME45
values('메롱','st002','ehalhtf',5)

insert into KOPO_PRODUCT_VOLUME45
values('메롱','오','아',45)
   
insert into KOPO_PRODUCT_VOLUME45
VALUES ('메롱','오','아',45)

INSERT INTO 표명
VALUES('메롱','오','아',45)

SELECT *
FROM KOPO_PRODUCT_VOLUME

UPDATE KOPO_PRODUCT_VOLUME
SET YEARWEEK = '201513'
WHERE 1=1
AND YEARWEEK = '201512'
AND PRODUCTGROUP = 'ST0001'

UPDATE KOPO_PRODUCT_VOLUME
SET YEARWEEK = '201514'
WHERE 1=1
AND YEARWEEK = '201523'
AND PRODUCTGROUP = 'ST0001'

DELETE FROM KOPO_PRODUCT_VOLUME
WHERE YEARWEEK = '201513'

SELECT *
FROM KOPO_PRODUCT_VOLUME_A02

SELECT * 
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND YEARWEEK = '201601'
AND PRODUCTGROUP = 'ST0001'

SELECT REGIONID, PRODUCTGROUP,YEARWEEK,VOLUME
    FROM KOPO_PRODUCT_VOLUME
UNION 
SELECT REGIONID, PRODUCTGROUP,YEARWEEK,VOLUME
    FROM KOPO_PRODUCT_VOLUME_A02

SELECT PRODUCTGROUP, YEARWEEK, VOLUME
FROM KOPO_PRODUCT_VOLUME

SELECT
'201701_테스트배치' AS PLANID,
REGIONID
FROM KOPO_PRODUCT_VOLUME

SELECT *
FROM KOPO_PRODUCT_VOLUME

SELECT
'201701_테스트배치' AS PLANID,
REGIONID
FROM KOPO_PRODUCT_VOLUME

SELECT
REGIONID ||'*'|| PRODUCTGROUP as PLANID,
REGIONID
FROM KOPO_PRODUCT_VOLUME

SELECT
PRODUCTGROUP ||'*'||YEARWEEK AS PLANUP,
PRODUCTGROUP
FROM KOPO_PRODUCT_VOLUME

SELECT *
FROM KOPO_PRODUCT_VOLUME

SELECT
'KOPO_D510' AS MEASUREID,
VOLUME
FROM KOPO_PRODUCT_VOLUME

SELECT 
    DISTINCT REGIONID, PRODUCTGROUP
FROM KOPO_PRODUCT_VOLUME

SELECT
    DISTINCT REGIONID, PRODUCTGROUP AS PRODUCT
FROM KOPO_PRODUCT_VOLUME

SELECT 
    REGIONID,PRODUCTGROUP, YEARWEEK,VOLUME
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK >= '201501'

SELECT *
FROM KOPO_PRODUCT_VOLUME

SELECT 
    REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME,
    ROUND(VOLUME * 1.1,3) AS WEIGHTED_VOL
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK >= '201501'

SELECT*
FROM KOPO_PROMOTION

SELECT
    ROUND(PMAP * 0.9,3) AS PMAP10
FROM KOPO_PROMOTION

SELECT 
    REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544'

SELECT *
FROM KOPO_PROMOTION

SELECT
REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544'

SELECT 
    TARGETWEEK,PMAP
FROM KOPO_PROMOTION
WHERE PMAP = &PAMP
OR TARGETWEEK <= 201503
OR TARGETWEEK >= 201501

SELECT
REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 
201503
ORDER BY YEARWEEK

SELECT
REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK

SELECT
    REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY DESC YEARWEEK

SELECT A.*,
    CONCAT(REGIONID, PRODUCTGROUP) AS IDX,
    REGIONID||'_'||PRODUCTGROUP AS IDX2,
    CONCAT(REGIONID,CONCAT(PRODUCTGROUP,YEARWEEK)) AS KEY_VALUE
FROM KOPO_PRODUCT_VOLUME A

SELECT A.*,
    CONCAT(REGIONID, PRODUCTGROUP) AS IDX,
    REGIONID||'_'||PRODUCTGROUP AS IDX2,
    CONCAT(REGIONID, CONCAT(PRODUCTGROUP,YEARWEEK)) AS KEY_VALUE
FROM KOPO_PRODUCT_VOLUME A

	SELECT 
	    SUBSTR(A.YEARWEEK,0,4) AS YEAR,
	    SUBSTR(A.YEARWEEK,5,6) AS WEEK,
	    A.* 
	FROM KOPO_PRODUCT_VOLUME A


	SELECT A.*,
       RPAD( UPPER(CUSTID), 3, 0) AS CSID
	FROM CUSTOMERDATA A   
	
    SELECT A.*,
       LPAD( CUSTID, 12, '*') AS CUSTOMERCODE
	FROM CUSTOMERDATA A
	