SELECT * 
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND PRODUCTGROUP = &intv
AND YEARWEEK = &INYEARWEEK

SELECT AP2ID, SALESID, ITEM, YEARWEEK, QTY 
FROM KOPO_CHANNEL_RESULT
ORDER BY AP2ID, SALESID, ITEM, YEARWEEK DESC, QTY --정렬

  
SELECT REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
ORDER BY REGIONID DESC, PRODUCTGROUP, YEARWEEK ASC

SELECT DISTINCT YEARWEEK
FROM(
    SELECT *
    FROM KOPO_CHANNEL_RESULT
    WHERE YEARWEEK IN ('201720','201721')
)

SELECT LOWER(PRODUCTGROUP) AS PRODUCTNAME
FROM KOPO_PRODUCT_VOLUME

CREATE TABLE LOGIN_TABLE(
ID VARCHAR2(100),
PASS VARCHAR2(100))

SELECT *
FROM LOGIN_TABLE

INSERT INTO LOGIN_TABLE VALUES('manager','1234')

SELECT *
FROM LOGIN_TABLE
WHERE UPPER(ID) = UPPER('hAiteam')

SELECT A.*,
        CONCAT(REGIONID, PRODUCTGROUP) AS IDX,
        REGIONID||'_'||PRODUCTGROUP AS IDX2,
        CONCAT(REGIONID,CONCAT(PRODUCTGROUP,YEARWEEK)) AS KEY_VALUE
FROM KOPO_PRODUCT_VOLUME A 

SELECT SUBSTR(A.PRODUCTGROUP,0,3) AS CASE1,
        A.*
FROM KOPO_PRODUCT_VOLUME A

SELECT 
    SUBSTR(A.YEARWEEK,0,4) AS YEAR, -- 시작포인트부터 4개를 가져온다.
    SUBSTR(A.YEARWEEK,5,2) AS WEEK, -- 5번부터 2개를 추출한다. 
    A.*
FROM KOPO_PRODUCT_VOLUME A

SELECT A.*,
       LPAD( UPPER(CUSTID), 10, '*') AS CSID
FROM CUSTOMERDATA A

SELECT A.*,
       RPAD( UPPER(CUSTID), 3, 0) AS CSID
FROM CUSTOMERDATA A   

SELECT A.*,
       LPAD( CUSTID, 12, '*') AS CUSTOMERCODE
FROM CUSTOMERDATA A 


-- TRIM (공백제거)
-- TRIM NULL 처리 TRIM...이후 NULL체크를!!!
SELECT LENGTH(TRIM('    AAAA    ')) AS CASE1
FROM DUAL
SUBSTR --추출

SELECT A.*,
       -- LTRIM(A.PRODUCTGROUP,
       TRIM (A.PRODUCT, 'PRO')
FROM KOPO_PRODUCT_VOLUME A

SELECT REPLACE(A.REGIONID,'A','NATION_') AS REGIONID,
       A.*
FROM KOPO_CHANNEL_SEASONALITY_NEW A

-- KOPO_CUSTOMERDATA의 고객코드는10자리이다 만약 10자리가 아니면 왼쪽에 0으로 채운다.이후 고객코드의 뒷 4자리는 암호화를 위해 * 처리를해야합니다.

SELECT A.*, 
    LPAD( CUSTOMERCODE, 10, '0') AS CSCODE,
    REPLACE(SUBSTR(CSCODE,7,3),'*')),
FROM KOPO_CUSTOMERDATA A

