SELECT A.*,
    SUBSTR(A.YEARWEEK,0,4) AS YEAR,
    SUBSTR(A.YEARWEEK,5,2) AS WEEK,
    MOD(20,4) AS TEST
FROM KOPO_PRODUCT_VOLUME A

SELECT POWER( 10,4)
FROM DUAL
-------------------------------------------------------------
SELECT *
FROM NUMBER_EXAMPLE

SELECT A.FIRST_NUMBER,
    A.SECOND_NUMBER,
    A.FIRST_NUMBER/SECOND_NUMBER AS AVG_NUM,
    ROUND(A.FIRST_NUMBER/A.SECOND_NUMBER) AS ROUND_NUM,
    FLOOR(A.FIRST_NUMBER/A.SECOND_NUMBER) AS FLOOR_NUM,
FROM NUMBER_EXAMPLE A
-------------------------------------------------------------

SELECT A.*
        ABS( A.FCST-A.ACTUAL ) AS DIFF,
        1-ABS( A.FCST-A.ACTUAL ) AS ACC1,
        1-ABS( A.FCST-A.ACTUAL ) / A.FCST AS ACCURACY
FROM RMSE_MAE_EXAMPLE A 

--날짜 함수

SELECT A.*,
       SYSDATE AS TIME_TAG
FROM KOPO_PRODUCT_VOLUME A

SELECT SYSDATE
FROM DUAL

SELECT 
    NEXT_DAY(SYSDATE,2),
    LAST_DAY(SYSDATE)
FROM DUAL

SELECT A.*
       SUBSTR(A.YEARWEEK,0,4) AS YEAR,
       MOD( SUBSTR(A.YEARWEEK,5,2), 4) AS WEEK1,
       MOD( TO_NUMBER( SUBSTR(A.YEARWEEK,5,2) ), 4) AS SIGNAL
FROM KOPO_PRODUCT_VOLUME A
ORDER BY REGIONID, PRODUCTGROUP, YEARWEEK


SELECT TO_CHAR(SYSDATE-7, 'YYYYMMDD') FROM DUAL

SELECT TO_CHAR(SYSDATE-3, 'YYYY_MM_DD') 
FROM DUAL

---CASE---
SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW
SELECT * 
FROM
(    SELECT A.REGIONID,
           A.PRODUCT,
           A.QTY,
           CASE WHEN A.QTY < 0 THEN 0
                WHEN A.QTY < 1000000 THEN 1000000
                ELSE A.QTY
           END AS REFINED_QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW A
)
WHERE 1=1
AND QTY < 0
AND REFINED_QTY 


-----DECODE----

SELECT *
FROM KOPO_CUSTOMERDATA A

SELECT A.*
       UPPER(GENDER) AS GENDER_CHANGE,
FROM KOPO_CUSTOMERDATA A

SELECT A.*
       --UPPER(A.GENDER) AS GENDER_CHANGE,
       ,DECODE(A.GENDER,'MALE',1,'FEMALE',2,0) AS SORT_ORDER
       FROM KOPO_CUSTOMERDATA A
WHERE 1=1
ORDER BY SORT_ORDER


--실습문제 --

SELECT *
FROM 
(
    SELECT A.TOTAL_AMOUNT,
           CASE WHEN A.TOTAL_AMOUNT >= 100000 THEN 'HIGH'
                WHEN A.TOTAL_AMOUNT < 100000 THEN 'LOW'
           END AS CUSTOMER_SEG
    FROM KOPO_CUSTOMERDATA A
);


SELECT *
FROM DT_RESULT_FINAL3

SELECT A.*
        CASE WHEN PRE_QTY = 0 THEN 0;
        CASE WHEN ((1-ABS((A.PRE_QTY - A.REAL_QTY))/A.PRE_QTY) = 0 THEN 0
        END AS ACCURACY 
FROM DT_RESULT_FINAL3 A

SELECT A.*,
       NVL(VOLUME, 20) AS NVL_EX,
       NVL2(VOLUME, VOLUME*1.5, 20) AS NVL2_EX
FROM NVL_CHECK A

       