--문제1
SELECT
    CONCAT(REGIONID,'_'),A,PRODUCTGROUP) AS IDX,
    -- REGIONID||'_'||PRODUCTGROUP AS IDX,
    A.*
FROM KOPO_PRODUCT_VOLUME A

--문제2
SELECT *
FROM PRO_PROMOTION

SELECT *
FROM PRO_RECALL_ITEM

SELECT DISTINCT ITEM
FROM(
    SELECT *
    FROM PRO_PROMOTION
    WHERE 1=1
    AND ITEM IN(    SELECT ITEM_PREFIX||ITEM_CODE
                    FROM PRO_RECALL_ITEM    )
)


SELECT 
    SUBSTR(A.ITEM,0,4)AS ITEM_PREFIX,
    SUBSTR(A.ITEM,5,8)AS ITEM_CODE,
    A.*
FROM PRO_PROMOTION A


SELECT *
FROM PRO_PROMOTION A
WHERE 1=1
AND ITEM_CODE IN ('0211','0057','0308','0156','0095')

