CREATE TABLE KOPO_PRODUCT_VOLUME(
    REGIONID VARCHAR2(100),
    PRODUCTGROUP VARCHAR2(100),
    YEARWEEK NUMBER,
    VOLUME NUMBER)
    
SELECT *
FROM KOPO_PRODUCT_VOLUME

INSERT INTO KOPO_PRODUCT_VOLUME
VALUES('A01','ST0001','201501',5000)

INSERT INTO KOPO_PRODUCT_VOLUME
SELECT REGIONID,'ST0003',YEARWEEK,VOLUME
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'

INSERT ALL
    INTO KOPO_PRODUCT_VOLUME2 (REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME)
        VALUES (REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME)
    INTO KOPO_PRODUCT_VOLUME3 (REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME)
        VALUES (REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME)
SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1;

CREATE TABLE KOPO_PRODUCT_VOLUME2 (
    REGIONID VARCHAR2(40),
    PRODUCTGROUP VARCHAR2(40),
    YEARWEEK VARCHAR2(6),
    VOLUME NUMBER
);

SELECT *
FROM KOPO_PRODUCT_VOLUME2

UPDATE KOPO_PRODUCT_VOLUME2
SET PRODUCTGROUP ='ST0003'
WHERE 1=1
AND PRODUCTGROUP ='ST0001'

SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW

CREATE TABLE KOPO_CHANNEL_SEASONALITY_NEW2(
    REGIONID VARCHAR2(100),
    PRODUCT VARCHAR2(100),
    YEARWEEK NUMBER,
    QTY NUMBER)
    
SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW2

INSERT INTO KOPO_CHANNEL_SEASONALITY_NEW2
SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW

SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW2


    